CREATE DATABASE productsdb IF NOT EXISTS;

use productsdb;

CREATE TABLE IF NOT EXISTS product (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    price DECIMAL(10,2),
    createAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

describe product;